# Generated by Django 4.2.7 on 2024-02-01 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonUser",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basemodel",
                    ),
                ),
                ("time_watched", models.IntegerField(default=0)),
                ("totel_time", models.IntegerField(default=0)),
            ],
            bases=("main.basemodel",),
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="seconds",
            new_name="totel_time",
        ),
        migrations.AddField(
            model_name="lesson",
            name="author",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(default="templates/users/Azimjohn.MP4", upload_to="course/videos/"),
        ),
        migrations.CreateModel(
            name="LessonUserWatched",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.basemodel",
                    ),
                ),
                ("from_time", models.IntegerField(default=0)),
                ("to_time", models.IntegerField(default=0)),
                (
                    "lesson_user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.lessonuser"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=("main.basemodel",),
        ),
        migrations.AddField(
            model_name="lessonuser",
            name="lesson_us",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.lesson"),
        ),
        migrations.AddField(
            model_name="lessonuser",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
