# Generated by Django 4.2.7 on 2024-02-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_lessonuser_rename_seconds_lesson_totel_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonuser",
            name="totel_time",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
