# Generated by Django 4.2.7 on 2024-02-01 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0003_alter_lessonuser_totel_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="totel_time",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(blank=True, default="templates/users/Azimjohn.MP4", upload_to="course/videos/"),
        ),
    ]
