# Generated by Django 4.2.7 on 2024-02-01 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0004_alter_course_author_alter_course_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="buy_user",
            field=models.ManyToManyField(blank=True, related_name="buy_course", to=settings.AUTH_USER_MODEL),
        ),
    ]
