# Generated by Django 4.2.7 on 2024-02-01 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_course_category_of_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="discount_price",
            new_name="price_discount",
        ),
    ]
