# Generated by Django 4.2.7 on 2024-02-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_rename_discount_price_course_price_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonuser",
            name="lesson_us",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="lesson_user", to="course.lesson"
            ),
        ),
    ]
