# Generated by Django 4.2.7 on 2024-02-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0008_alter_lessonuser_lesson_us"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent_commentid",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
