# Generated by Django 4.2.7 on 2024-02-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0009_comment_parent_commentid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.FileField(blank=True, default="thumbnail/download.jpeg", null=True, upload_to="courses/"),
        ),
    ]
