# Generated by Django 4.2.7 on 2024-02-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0010_alter_course_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent_commentid",
        ),
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.FileField(blank=True, default="thumbnail/download", null=True, upload_to="courses/"),
        ),
    ]
