# Generated by Django 4.2.7 on 2024-02-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0011_remove_comment_parent_commentid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="course_of_comment",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="course.course"
            ),
        ),
    ]
