# Generated by Django 4.2.7 on 2024-02-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0012_alter_comment_course_of_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonuser",
            name="paused_time",
            field=models.IntegerField(default=0),
        ),
    ]
